import type { Metadata } from "next";
import { Space_Grotesk, Space_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import AuthToastHandler from "../components/ui/sonner";

// 🔹 Main UI font (clean + modern)
const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
});

// 🔹 Mono font (for code, terminal style)
const spaceMono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"], // Space Mono needs weights
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        spaceGrotesk.variable,
        spaceMono.variable,
        "font-sans"
      )}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster />
        <AuthToastHandler />
      </body>
    </html>
  );
}